import './styles/fonts.css'
import './styles/base.css'
import './styles/buttons.css'
import './styles/tablet.css'
import './styles/desktop.css'
import './js/get-questions.js'
import './js/buttons.js'
import './styles/questions.css'